<script context="module">
  export const ssr = false;

  export const load = async ({ url, params }) => {
    const qlikTicket = url.searchParams.get("qlikTicket");

    if (qlikTicket) {
      const qlikStylesURL = `https://${qsHost}/resources/autogenerated/qlik-styles.css?QlikTicket=${qlikTicket}`;

      const qlikStylesResponse = await fetch(qlikStylesURL, {
        credentials: "include",
      });
    }

    return true;
  };
</script>

<script>
  import { goto } from "$app/navigation";
  import enigma from "enigma.js";
  import schema from "enigma.js/schemas/12.67.2.json";

  const qsHost = "my-sense-instance.com";
  const reloadURI = `http://localhost:3000`;
  const xrfkey = "1234567890123456";
  const qsReloadTasksURL = `https://${qsHost}/qrs/reloadtask?Xrfkey=${xrfkey}`;

  let qlikApps = [];
  let qlikReloadTasks = [];

  const session = enigma.create({
    schema,
    url: `wss://${qsHost}/app/engineData?reloadURI=${encodeURIComponent(
      reloadURI
    )}`,
    createSocket: (url) => new WebSocket(url),
  });

  session.on("notification:OnAuthenticationInformation", (data) => {
    if (data.loginUri) goto(data.loginUri);
  });

  session.on("notification:OnConnected", async () => {
    qlikReloadTasks = await fetch(qsReloadTasksURL, {
      credentials: "include",
      headers: {
        "X-Qlik-Xrfkey": `${xrfkey}`,
      },
    }).then((res) => res.json());
  });

  (async function () {
    let global = await session.open();
    qlikApps = await global.getDocList();
    await session.close();
  })();
</script>

<main>
  <div>
    <h1>Qlik apps:</h1>

    {#each qlikApps as qlikApp}
      <div title={qlikApp.qDocId}>{qlikApp.qDocName}</div>
    {/each}
  </div>
  <div>
    <h1>Qlik Reload Tasks:</h1>

    {#each qlikReloadTasks as reloadTask}
      <div title={reloadTask.id}>{reloadTask.name}</div>
    {/each}
  </div>
</main>

<style>
  main {
    padding: 1em;
    margin: 0 auto;
    display: grid;
    grid-template-columns: 50% 50%;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4rem;
    font-weight: 100;
    line-height: 1.1;
  }
</style>
